apiVersion: v1
kind: ServiceAccount
metadata:
  name: kcm
  namespace: kcm
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
    name: kcm
rules:
  - apiGroups: ["*"]
    resources: ["certificates", "ingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["*"]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: ["*"]
    resources: ["events"]
    verbs: ["create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kcm
subjects:
  - kind: ServiceAccount
    namespace: kcm
    name: kcm
roleRef:
  kind: ClusterRole
  name: kcm
  apiGroup: rbac.authorization.k8s.io
